#pragma once

#include "CommandTable.h"

extern CommandInfo kCommandInfo_LoadEffect;
extern CommandInfo kCommandInfo_EnableEffect;
extern CommandInfo kCommandInfo_DisableEffect;
extern CommandInfo kCommandInfo_ReleaseEffect;
extern CommandInfo kCommandInfo_SetEffectConstantB;
extern CommandInfo kCommandInfo_SetEffectConstantI;
extern CommandInfo kCommandInfo_SetEffectConstantF;
extern CommandInfo kCommandInfo_SetEffectConstantV;
extern CommandInfo kCommandInfo_SetEffectSamplerTexture;
extern CommandInfo kCommandInfo_IsEffectEnabled;

#ifndef	NO_DEPRECATED
extern CommandInfo kCommandInfo_LoadShader;
extern CommandInfo kCommandInfo_ApplyFullscreenShader;
extern CommandInfo kCommandInfo_RemoveFullscreenShader;
extern CommandInfo kCommandInfo_SetShaderInt;
extern CommandInfo kCommandInfo_SetShaderFloat;
extern CommandInfo kCommandInfo_SetShaderVector;
extern CommandInfo kCommandInfo_SetShaderTexture;
extern CommandInfo kCommandInfo_IsShaderEnabled;
#endif
