#pragma once

#include "CommandTable.h"

extern CommandInfo kCommandInfo_LoadEffect;
extern CommandInfo kCommandInfo_ApplyFullscreenShader;
extern CommandInfo kCommandInfo_RemoveFullscreenShader;
extern CommandInfo kCommandInfo_SetEffectInt;
extern CommandInfo kCommandInfo_SetEffectFloat;
extern CommandInfo kCommandInfo_SetEffectVector;
extern CommandInfo kCommandInfo_SetEffectTexture;
extern CommandInfo kCommandInfo_IsEffectEnabled;